image:
  file: .gitpod.Dockerfile

tasks:
  - name: Database
    command: >
      mongod & &&
      mongoimport --db test --collection beers beers/AffligemBlond.json && 
      mongoimport --db test --collection beers beers/AffligemDubbel.json &&
      mongoimport --db test --collection beers beers/AffligemTripel.json &&
      mongoimport --db test --collection beers beers/ChimayRed.json &&
      mongoimport --db test --collection beers beers/ChimayTriple.json &&
      mongoimport --db test --collection beers beers/StBernardusAbt12.json &&
      mongoimport --db test --collection beers beers/StBernardusPater6.json &&
      mongoimport --db test --collection beers beers/StBernardusTriple.json &&
      mongoimport --db test --collection beers beers/TrappistesRochefort6.json &&
      mongoimport --db test --collection beers beers/TrappistesRochefort8.json &&
      mongoimport --db test --collection beers beers/TrappistesRochefort10.json &&  

ports:
  - port: 3000
    onOpen: notify
    visibility: public   