image:
  file: .gitpod.Dockerfile

tasks:
  - name: Database
    command: mongod 
  - command: >
      gp await-port 27017 &&
      mongoimport --db test --collection beers beers/AffligemBlond.json
  - command: >
      gp await-port 27017 &&
      mongoimport --db test --collection beers beers/AffligemDubbel.json
  - command: >
      gp await-port 27017 &&
      mongoimport --db test --collection beers beers/AffligemTripel.json
  - command: >
      gp await-port 27017 &&
      mongoimport --db test --collection beers beers/ChimayRed.json
  - command: >
      gp await-port 27017 &&
      mongoimport --db test --collection beers beers/ChimayTriple.json
  - command: >
      gp await-port 27017 &&
      mongoimport --db test --collection beers beers/StBernardusAbt12.json
  - command: >
      gp await-port 27017 &&
      mongoimport --db test --collection beers beers/StBernardusPater6.json
  - command: >
      gp await-port 27017 &&
      mongoimport --db test --collection beers beers/StBernardusTriple.json
  - command: >
      gp await-port 27017 &&
      mongoimport --db test --collection beers beers/TrappistesRochefort6.json
  - command: >
      gp await-port 27017 &&
      mongoimport --db test --collection beers beers/TrappistesRochefort8.json
  - command: >
      gp await-port 27017 &&
      mongoimport --db test --collection beers beers/TrappistesRochefort10.json
  - name: Node
    before: npm install
    command: node index.js

ports:
  - port: 3000
    onOpen: notify
    visibility: public   